"""Added reporting_year column to TRI_reporting_form and TRI_facility_history

Revision ID: 65d18549c00e
Revises: 7f2299b265eb
Create Date: 2026-05-12 15:51:03.613519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d18549c00e'
down_revision: Union[str, Sequence[str], None] = '7f2299b265eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tri_facility_history', sa.Column('reporting_year', sa.Integer(), nullable=True))
    op.add_column('tri_reporting_form', sa.Column('reporting_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tri_reporting_form', 'reporting_year')
    op.drop_column('tri_facility_history', 'reporting_year')
    # ### end Alembic commands ###
