"""Added indexes to every doc_ctrl_num, tri_facility_id, and tri_chem_id

Revision ID: 7f2299b265eb
Revises: b6f94bc27b11
Create Date: 2026-05-12 13:24:48.385596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2299b265eb'
down_revision: Union[str, Sequence[str], None] = 'b6f94bc27b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tri_chem_activity_doc_ctrl_num'), 'tri_chem_activity', ['doc_ctrl_num'], unique=False)
    op.create_index(op.f('ix_tri_facility_db_tri_facility_id'), 'tri_facility_db', ['tri_facility_id'], unique=False)
    op.create_index(op.f('ix_tri_facility_history_tri_facility_id'), 'tri_facility_history', ['tri_facility_id'], unique=False)
    op.create_index(op.f('ix_tri_facility_npdes_tri_facility_id'), 'tri_facility_npdes', ['tri_facility_id'], unique=False)
    op.create_index(op.f('ix_tri_facility_rcra_tri_facility_id'), 'tri_facility_rcra', ['tri_facility_id'], unique=False)
    op.create_index(op.f('ix_tri_facility_uic_tri_facility_id'), 'tri_facility_uic', ['tri_facility_id'], unique=False)
    op.create_index(op.f('ix_tri_form_total_doc_ctrl_num'), 'tri_form_total', ['doc_ctrl_num'], unique=False)
    op.create_index(op.f('ix_tri_reporting_form_tri_chem_id'), 'tri_reporting_form', ['tri_chem_id'], unique=False)
    op.create_index(op.f('ix_tri_submission_naics_doc_ctrl_num'), 'tri_submission_naics', ['doc_ctrl_num'], unique=False)
    op.create_index(op.f('ix_tri_submission_naics_tri_facility_id'), 'tri_submission_naics', ['tri_facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tri_submission_naics_tri_facility_id'), table_name='tri_submission_naics')
    op.drop_index(op.f('ix_tri_submission_naics_doc_ctrl_num'), table_name='tri_submission_naics')
    op.drop_index(op.f('ix_tri_reporting_form_tri_chem_id'), table_name='tri_reporting_form')
    op.drop_index(op.f('ix_tri_form_total_doc_ctrl_num'), table_name='tri_form_total')
    op.drop_index(op.f('ix_tri_facility_uic_tri_facility_id'), table_name='tri_facility_uic')
    op.drop_index(op.f('ix_tri_facility_rcra_tri_facility_id'), table_name='tri_facility_rcra')
    op.drop_index(op.f('ix_tri_facility_npdes_tri_facility_id'), table_name='tri_facility_npdes')
    op.drop_index(op.f('ix_tri_facility_history_tri_facility_id'), table_name='tri_facility_history')
    op.drop_index(op.f('ix_tri_facility_db_tri_facility_id'), table_name='tri_facility_db')
    op.drop_index(op.f('ix_tri_chem_activity_doc_ctrl_num'), table_name='tri_chem_activity')
    # ### end Alembic commands ###
