"""Increased parent_name length from 20 to 50

Revision ID: a56941fbbc2d
Revises: 
Create Date: 2026-04-29 15:45:15.055862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56941fbbc2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tri_chem_activity', ['doc_ctrl_num'])
    op.alter_column('tri_facility_history', 'parent_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_unique_constraint(None, 'tri_form_total', ['doc_ctrl_num'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tri_form_total', type_='unique')
    op.alter_column('tri_facility_history', 'parent_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'tri_chem_activity', type_='unique')
    # ### end Alembic commands ###
