"""Added tri_submission_naics and naics_code tables

Revision ID: b6f94bc27b11
Revises: 264c2b19a9b9
Create Date: 2026-05-09 15:52:22.328419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f94bc27b11'
down_revision: Union[str, Sequence[str], None] = '264c2b19a9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naics_code',
    sa.Column('naics_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('naics_code')
    )
    op.create_table('tri_submission_naics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tri_facility_id', sa.String(length=15), nullable=False),
    sa.Column('doc_ctrl_num', sa.String(length=13), nullable=True),
    sa.Column('naics_code', sa.String(length=6), nullable=True),
    sa.Column('industry_code', sa.String(length=6), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['doc_ctrl_num'], ['tri_reporting_form.doc_ctrl_num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tri_submission_naics')
    op.drop_table('naics_code')
    # ### end Alembic commands ###
